### ISSUE TITLE
Glyph download timeouts

### ISSUE THREAD

**Issue by minusfive** [caksoylar/zmk-config#6]
Have been experiencing regular timeouts / failures, seem related to the glyphs download step: https://github.com/minusfive/zmk-config/actions/runs/11321454822/job/31500930916

```sh
INFO: using config args: -c keymap-drawer/config.yaml
INFO: drawing for corneish_zen
INFO:   got extra parse args: 
INFO:   got extra draw args: 
Traceback (most recent call last):
  File "/home/runner/.local/bin/keymap", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.local/lib/python3.10/site-packages/keymap_drawer/__main__.py", line 212, in main
    draw(args, config.draw_config)
  File "/home/runner/.local/lib/python3.10/site-packages/keymap_drawer/__main__.py", line 43, in draw
    drawer = KeymapDrawer(
  File "/home/runner/.local/lib/python3.10/site-packages/keymap_drawer/draw/draw.py", line 25, in __init__
    self.init_glyphs()
  File "/home/runner/.local/lib/python3.10/site-packages/keymap_drawer/draw/glyph.py", line 58, in init_glyphs
    self.name_to_svg |= self._fetch_glyphs(rest)
  File "/home/runner/.local/lib/python3.10/site-packages/keymap_drawer/draw/glyph.py", line 88, in _fetch_glyphs
    return dict(zip(names, p.map(fetch_fn, names, urls, timeout=FETCH_TIMEOUT)))
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 623, in result_iterator
    yield _result_or_cancel(fs.pop(), end_time - time.monotonic())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 460, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError
ERROR: parsing or drawing failed for corneish_zen!
Error: Process completed with exit code 1.
```

Started noticing a few days ago, where about 50% of jobs failed. Then it's gradually gone up until the last 6 runs have consistently failed: https://github.com/minusfive/zmk-config/actions/runs/11321454822/usage

**Comment by minusfive** [comment]
LOL, just noticed I submitted this to your config repo instead of `keymap-drawer` 🤦
